name: On New Release

on: [repository_dispatch]

jobs:
  create-pull-request:
    if: github.event.action == 'lsp-add-or-update-package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: make-pr
        run: python3 auto-update-repository.py <<<'${{ toJson(github.event.client_payload) }}'
      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: '${{ steps.make-pr.outputs.commit_message }}'
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          delete-branch: true
          branch-suffix: random
          title: '${{ steps.make-pr.outputs.pr_title }}'
          body: '${{ steps.make-pr.outputs.pr_body }}'
